version: '0.1.{build}'

nuget:
  project_feed: true

configuration: Release

only_commits:
  files:
    - ps/
    - src/
    - tools/
    - appveyor.yml

image: Visual Studio 2017

branches:
  only:
    - master
    - development

environment:
  BUILD_ALL_PLATFORMS: 1
  APITOKEN:
    secure: 5TI2LVqKI0e9RN6tfKGY1kOGqQPnzVT5nVvGhEmNXZ4=
  KEYSECRET:
    secure: R5dL3BcCgnJ4e8l7CXVC+PORgj+8Z/4seFazfXiYZUAzoxFZOpj7GT3/S00dO72vAkKhvsGCPPfnKZAf12WZXj7rOJDaM8OSuvUifZdQ7Oo=

init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0");
      
install:
  - ps: >-
      if ("$Env:APPVEYOR_PULL_REQUEST_NUMBER" -eq "") 
      { 
        nuget install secure-file -ExcludeVersion;
        secure-file\tools\secure-file -decrypt key\Key.snk.enc -secret $env:KEYSECRET
      }

before_build:
  - msbuild /t:restore /v:minimal src

build_script:
  - msbuild /t:build src
  - ps: .\ps\GetChangesSinceLastBuild.ps1 -ApiToken $Env:APITOKEN | % { msbuild /t:pack "$_" /p:PackageOutputPath=..\..\artifacts }

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/connectql/api/v2/package
    api_key:
      secure: sAyhaazWBYVsEH2NC2YAFSxBM447yIouEYsXuoCqP2n7q/OzzMsjcpAuovZzjvff
    skip_symbols: true
  - provider: NuGet
    server: https://www.myget.org/F/connectql/vsix/api/v2/package
    api_key:
      secure: sAyhaazWBYVsEH2NC2YAFSxBM447yIouEYsXuoCqP2n7q/OzzMsjcpAuovZzjvff
    skip_symbols: true
    artifact: /.*\.vsix/

test_script:
  - dotnet test "src\ConnectQl.Tests\ConnectQl.Tests.csproj" --no-build --no-restore

artifacts:
  - path: artifacts\**\*.*

