nuget:
  project_feed: true

configuration: Release

only_commits:
  files:
    - ps/
    - src/
    - tools/
    - appveyor.yml
    - codecov.yml

image: Visual Studio 2017

branches:
  only:
    - master
    - development

environment:
  BUILD_ALL_PLATFORMS: 1
  MYGETAPITOKEN:
    secure: sAyhaazWBYVsEH2NC2YAFSxBM447yIouEYsXuoCqP2n7q/OzzMsjcpAuovZzjvff
  APITOKEN:
    secure: 5TI2LVqKI0e9RN6tfKGY1kOGqQPnzVT5nVvGhEmNXZ4=
  KEYSECRET:
    secure: R5dL3BcCgnJ4e8l7CXVC+PORgj+8Z/4seFazfXiYZUAzoxFZOpj7GT3/S00dO72vAkKhvsGCPPfnKZAf12WZXj7rOJDaM8OSuvUifZdQ7Oo=

init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0");

install:
  - ps: >-
      if ("$Env:APPVEYOR_PULL_REQUEST_NUMBER" -eq "") 
      { 
        nuget install secure-file -ExcludeVersion;
        secure-file\tools\secure-file -decrypt key\Key.snk.enc -secret $env:KEYSECRET
      }
  - nuget install OpenCover -ExcludeVersion
  - nuget install xunit.runner.console -ExcludeVersion
  - choco install gitversion.portable -pre -y
  - choco install codecov
  
before_build:
  - msbuild /t:restore /v:minimal src
  - ps: gitversion /l console /output buildserver

build_script:
  - md logs
  - msbuild /t:build src /bl:logs\Solution.binlog /p:Version=%GitVersion_NuGetVersion% /p:AssemblyVersion=%GitVersion_AssemblySemVer% /p:FileVersion=%GitVersion_MajorMinorPatch%.0 /p:InformationalVersion=%GitVersion_InformationalVersion% /p:VsixVersion=%GitVersion_MajorMinorPatch% /p:VsixPreReleaseVersion=%GitVersion_PreReleaseNumber% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: >-
      $packProjects = (.\ps\GetChangesSinceLastBuild.ps1 -ApiToken $Env:APITOKEN); 
      $packProjects | % { 
            msbuild /t:pack "$_" "/bl:logs\$($_.Name).binlog" /p:Version=$env:GitVersion_NuGetVersion /p:AssemblyVersion=$env:GitVersion_AssemblySemVer /p:FileVersion=$($env:GitVersion_MajorMinorPatch).0 /p:InformationalVersion=$env:GitVersion_InformationalVersion /p:VsixVersion=$env:GitVersion_MajorMinorPatch /p:VsixPreReleaseVersion=$env:GitVersion_PreReleaseNumber /p:PackageOutputPath=..\..\artifacts /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
      };
      .\ps\UpdatePackageReferences.ps1 -PackProjects $packProjects

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/connectql/api/v2/package
    api_key: 
      secure: sAyhaazWBYVsEH2NC2YAFSxBM447yIouEYsXuoCqP2n7q/OzzMsjcpAuovZzjvff
    skip_symbols: false
    symbol_server : https://www.myget.org/F/connectql/symbols/api/v2/package

after_deploy:
  - ps: ls artifacts\*.vsix | % { Invoke-RestMethod -Uri https://www.myget.org/F/connectql/vsix/upload -Method Post -InFile $_.FullName -Headers @{ "X-NuGet-ApiKey" = $env:MYGETAPITOKEN } }
  - ps: 7z a logs.zip logs\*.binlog
  - appveyor PushArtifact logs.zip

test_script:
  - tools\runcoverage.bat

artifacts:
  - path: artifacts\**\*.*
  
on_failure:
  - ps: 7z a logs.zip logs\*.binlog
  - appveyor PushArtifact logs.zip