version: '0.1.{build}'

configuration:
  - Release

only_commits:
  files:
    - src/
    - tools/

image: Visual Studio 2017

branches:
  only:
    - master
    - development

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  KEYSECRET:
    secure: R5dL3BcCgnJ4e8l7CXVC+PORgj+8Z/4seFazfXiYZUAzoxFZOpj7GT3/S00dO72vAkKhvsGCPPfnKZAf12WZXj7rOJDaM8OSuvUifZdQ7Oo=

init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt key\Key.snk.enc -secret %KEYSECRET%

before_build:
  - appveyor-retry msbuild /t:restore src /v:Minimal /p:BUILD_ALL_PLATFORMS=1

build_script:
  - msbuild /t:build "src" /p:Configuration=%CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION% /p:BUILD_ALL_PLATFORMS=1

after_build:
  - msbuild /t:pack "src\ConnectQl" /p:Configuration=%CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION% /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-prerelease /p:PackageOutputPath=..\..\artifacts /p:BUILD_ALL_PLATFORMS=1

test_script:
  - dotnet test "src\ConnectQl.Tests\ConnectQl.Tests.csproj" --no-build

artifacts:
  - path: artifacts\**\*.*

#on_finish: # Run the demo to show that it works
#- dotnet artifacts\ConsoleApplication\ConsoleApplication.dll
