nuget:
  project_feed: true

configuration: Release

only_commits:
  files:
    - ps/
    - src/
    - tools/
    - appveyor.yml
    - codecov.yml

image: Visual Studio 2017

branches:
  only:
    - master
    - development

environment:
  BUILD_ALL_PLATFORMS: 1
  MYGETAPITOKEN:
    secure: sAyhaazWBYVsEH2NC2YAFSxBM447yIouEYsXuoCqP2n7q/OzzMsjcpAuovZzjvff
  APITOKEN:
    secure: 5TI2LVqKI0e9RN6tfKGY1kOGqQPnzVT5nVvGhEmNXZ4=
  KEYSECRET:
    secure: R5dL3BcCgnJ4e8l7CXVC+PORgj+8Z/4seFazfXiYZUAzoxFZOpj7GT3/S00dO72vAkKhvsGCPPfnKZAf12WZXj7rOJDaM8OSuvUifZdQ7Oo=

init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0");

install:
  - ps: >-
      if ("$Env:APPVEYOR_PULL_REQUEST_NUMBER" -eq "") 
      { 
        nuget install secure-file -ExcludeVersion;
        secure-file\tools\secure-file -decrypt key\Key.snk.enc -secret $env:KEYSECRET
      }
  - nuget install OpenCover -ExcludeVersion
  - nuget install xunit.runner.console -ExcludeVersion
  - choco install gitversion.portable -pre -y
  - choco install codecov
  
before_build:
  - msbuild /t:restore /v:minimal src
  - ps: gitversion /l console /output buildserver

build_script:
  - SET Version=%GitVersion_NuGetVersion%
  - SET AssemblyVersion=%GitVersion_AssemblySemVer%
  - SET FileVersion=%GitVersion_MajorMinorPatch%.0
  - SET InformationalVersion=%GitVersion_InformationalVersion%
  - SET VsixVersion=%GitVersion_MajorMinorPatch%
  - SET VsixPreReleaseVersion=%GitVersion_PreReleaseNumber% 
  - SET PackageOutputPath=..\..\artifacts
  - msbuild /t:build src 
  - ps: >-
      $packProjects = (.\ps\GetChangesSinceLastBuild.ps1 -ApiToken $Env:APITOKEN); 
      $packProjects | % { msbuild /t:pack "$_" };
      .\ps\UpdatePackageReferences.ps1 -PackProjects $packProjects

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/connectql/api/v2/package
    api_key: 
      secure: sAyhaazWBYVsEH2NC2YAFSxBM447yIouEYsXuoCqP2n7q/OzzMsjcpAuovZzjvff
    skip_symbols: false
    symbol_server : https://www.myget.org/F/connectql/symbols/api/v2/package

after_deploy:
  - ps: ls artifacts\*.vsix | % { Invoke-RestMethod -Uri https://www.myget.org/F/connectql/vsix/upload -Method Post -InFile $_.FullName -Headers @{ "X-NuGet-ApiKey" = $env:MYGETAPITOKEN } }

test_script:
  - tools\runcoverage.bat

artifacts:
  - path: artifacts\**\*.*
