version: '0.1.{build}-prerelease'

configuration:
  - Release

image: Visual Studio 2017

branches:
  only:
    - master

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

before_build:
  - appveyor-retry msbuild /t:restore src /v:Minimal

build_script:
  - msbuild /t:build "src\ConnectQL" /p:Configuration=%CONFIGURATION% /p:Version=%VERSION%

after_build:
  - msbuild /t:pack "src\ConnectQL" /p:Configuration=%CONFIGURATION% /p:Version=%VERSION% /p:PackageOutputPath=artifacts

#test_script:
#- dotnet test "test\MyFirstUnitTests" -c %CONFIGURATION%

artifacts:
  - path: artifacts\**\*.*

cache:
  - '%USERPROFILE%\.nuget\packages'

#on_finish: # Run the demo to show that it works
#- dotnet artifacts\ConsoleApplication\ConsoleApplication.dll