version: '0.1.{build}'

nuget:
  project_feed: true

configuration: Release

only_commits:
  files:
    - src/
    - tools/
    - appveyor.yml

image: Visual Studio 2017

branches:
  only:
    - master
    - development

environment:
  APITOKEN:
    secure: 5TI2LVqKI0e9RN6tfKGY1kOGqQPnzVT5nVvGhEmNXZ4=
  KEYSECRET:
    secure: R5dL3BcCgnJ4e8l7CXVC+PORgj+8Z/4seFazfXiYZUAzoxFZOpj7GT3/S00dO72vAkKhvsGCPPfnKZAf12WZXj7rOJDaM8OSuvUifZdQ7Oo=

init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0");
      
install:
  - ps: >-
      if ("$Env:APPVEYOR_PULL_REQUEST_NUMBER" -eq "") 
      { 
        nuget install secure-file -ExcludeVersion;
        secure-file\tools\secure-file -decrypt key\Key.snk.enc -secret $env:KEYSECRET
      }

before_build:
  - msbuild /t:restore /v:minimal src /p:BUILD_ALL_PLATFORMS=1

build_script:
  - msbuild /t:build src /p:BUILD_ALL_PLATFORMS=1
  - ps: .\ps\GetChangesSinceLastBuild.ps1 -ApiToken $Env:APITOKEN | % { msbuild /t:pack "$_" /p:PackageOutputPath=..\..\artifacts /p:BUILD_ALL_PLATFORMS=1 }

test_script:
  - dotnet test "src\ConnectQl.Tests\ConnectQl.Tests.csproj" --no-build

artifacts:
  - path: artifacts\**\*.*
