//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectQl.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConnectQl.Resources.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a source with alias &apos;{0}&apos;..
        /// </summary>
        internal static string AliasAlreadyUsed {
            get {
                return ResourceManager.GetString("AliasAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias &apos;{0}&apos; is not defined..
        /// </summary>
        internal static string AliasNotDefined {
            get {
                return ResourceManager.GetString("AliasNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available plugins: {0}..
        /// </summary>
        internal static string AvailablePlugins {
            get {
                return ResourceManager.GetString("AvailablePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERROR: {0}#.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must have a source..
        /// </summary>
        internal static string FieldMustHaveASource {
            get {
                return ResourceManager.GetString("FieldMustHaveASource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; should return a data source..
        /// </summary>
        internal static string FunctionIsNoDataSource {
            get {
                return ResourceManager.GetString("FunctionIsNoDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; is not a data target..
        /// </summary>
        internal static string FunctionIsNoDataTarget {
            get {
                return ResourceManager.GetString("FunctionIsNoDataTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; is not a trigger..
        /// </summary>
        internal static string FunctionIsNoTrigger {
            get {
                return ResourceManager.GetString("FunctionIsNoTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; not found..
        /// </summary>
        internal static string FunctionNotFound {
            get {
                return ResourceManager.GetString("FunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAVING is only allowed when GROUP BY is used..
        /// </summary>
        internal static string HavingNotAllowed {
            get {
                return ResourceManager.GetString("HavingNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid scope..
        /// </summary>
        internal static string InvalidScope {
            get {
                return ResourceManager.GetString("InvalidScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing aggregate function for &apos;{0}&apos;..
        /// </summary>
        internal static string MissingAggregateFunction {
            get {
                return ResourceManager.GetString("MissingAggregateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string NodeTypeNotSupported {
            get {
                return ResourceManager.GetString("NodeTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; is not supported for types &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string OperatorNotSupported {
            get {
                return ResourceManager.GetString("OperatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin &apos;{0}&apos; was already enabled..
        /// </summary>
        internal static string PluginAlreadyEnabled {
            get {
                return ResourceManager.GetString("PluginAlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source &apos;{0}&apos; is referenced before it is declared..
        /// </summary>
        internal static string SourceReferencedBeforeDeclared {
            get {
                return ResourceManager.GetString("SourceReferencedBeforeDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeclared variable &apos;{0}&apos;..
        /// </summary>
        internal static string UndeclaredVariable {
            get {
                return ResourceManager.GetString("UndeclaredVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operator &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownOperator {
            get {
                return ResourceManager.GetString("UnknownOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {0} is not a data source..
        /// </summary>
        internal static string VariableIsNoDataSource {
            get {
                return ResourceManager.GetString("VariableIsNoDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; is not a data target..
        /// </summary>
        internal static string VariableIsNoDataTarget {
            get {
                return ResourceManager.GetString("VariableIsNoDataTarget", resourceCulture);
            }
        }
    }
}
